// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzyuvoqpkiauqtizdybn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6eXV2b3Fwa2lhdXF0aXpkeWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NzA2NTEsImV4cCI6MjA5NDQ0NjY1MX0.TuoUurMxuJzIWFkBnMuc-D-kJFHBGPauSGVVCXUhWhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});